build:
  id: 103453
  version: 2.0.1
  name: "Dev-Git-Configuration-Environment"
  type: "Git-Development-Build"

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest 
management:
  enpoints:
    web:
      exposure:
        include: "*"
