build:
  id: 103453
  version: 2.0.1
  name: "Dev-Git-Configuration-Environment-spring-cloud-bus-updated"
  type: "Git-Development-Build"

spring:
  
  # RabbitMQ Configuration
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    # virtual-host: /
management:
  endpoints:
    web:
      exposure:
        include: "*"
  # endpoint:
  #   health:
  #     show-details: always
  #   refresh:
  #     enabled: true
  #   bus-refresh:
  #     enabled: true
